services:
  yernar:
    build: .
    ports:
      - "9000:9000"
    networks:
      - postgres-network
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - proj_data:/yernar
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles

  db:
    image: library/postgres:13-alpine
    ports:
      - 5433:5433
    restart: unless-stopped
    networks:
      - postgres-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: proj
      POSTGRES_PASSWORD: Qqwerty1245!
      POSTGRES_DB: proj

networks:
  postgres-network:
    driver: bridge

volumes:
  proj_data:
  postgres_data: