# Generated by Django 5.1.4 on 2024-12-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='Автоматический генерируется', unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(help_text='Автоматический генерируется', unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(help_text='Автоматический генерируется', unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='slug',
            field=models.SlugField(help_text='Автоматический генерируется', unique=True, verbose_name='Ссылка'),
        ),
    ]
