# Generated by Django 5.1.4 on 2024-12-19 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTestimonialAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_attachment', models.ImageField(upload_to='testimonial/attachment/', verbose_name='Прикепленная фотография')),
            ],
            options={
                'verbose_name': 'Прикрепленный к отзыву фото',
                'verbose_name_plural': 'Прикрепленные к отзыву фотографии',
            },
        ),
        migrations.CreateModel(
            name='EventTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_author', models.CharField(max_length=150, verbose_name='Автор')),
                ('testimonial_content', models.CharField(max_length=200, verbose_name='Отзыв')),
                ('event_rate', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Оценка ивента')),
                ('testimonial_publish', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event', verbose_name='Ивент')),
                ('testimonial_attachments', models.ManyToManyField(blank=True, to='main.eventtestimonialattachment', verbose_name='Прикрепленные фотографии')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
