# Generated by Django 5.1.4 on 2024-12-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_article_slug_alter_event_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_artist',
            field=models.CharField(default='Pyrokinesis', max_length=150, verbose_name='Артист выступающий'),
            preserve_default=False,
        ),
    ]
