# Generated by Django 5.1.4 on 2024-12-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_bannerimages_alter_aboutus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimages',
            name='banner_image',
            field=models.ImageField(default='', upload_to='banner/images/', verbose_name='Картина на баннере'),
            preserve_default=False,
        ),
    ]
