# Generated by Django 5.1.4 on 2024-12-20 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_bannerimages_banner_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='HomePageModel',
        ),
    ]
