# Generated by Django 5.1.4 on 2024-12-20 09:49

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_homepage_homepagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('cover', models.ImageField(blank=True, upload_to='artist_cover')),
                ('detail', ckeditor.fields.RichTextField()),
                ('biographyh', ckeditor.fields.RichTextField()),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField()),
                ('origin', models.CharField(max_length=255)),
                ('years_of_activity', models.CharField(max_length=50, verbose_name='Годы активности')),
                ('awards', models.CharField(blank=True, max_length=50)),
                ('is_band_member', models.BooleanField(default=False)),
                ('website', models.URLField(blank=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=59)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_cover', models.ImageField(blank=True, upload_to='company_covers')),
                ('detail', ckeditor.fields.RichTextField(blank=True)),
                ('founded_date', models.DateField()),
                ('founders', models.CharField(blank=True, max_length=255)),
                ('headquarters', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('company_type', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_artist',
        ),
        migrations.AddField(
            model_name='event',
            name='parking',
            field=models.CharField(choices=[('Есть', 'Есть'), ('Нет', 'Нет')], default='Есть', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(blank=True, to='main.artist'),
        ),
        migrations.AddField(
            model_name='artist',
            name='labels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.label'),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='song_covers')),
                ('lyrics', ckeditor.fields.RichTextField(blank=True)),
                ('length', models.TimeField()),
                ('song_writers', models.CharField(blank=True, max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('video_url', models.URLField(blank=True)),
                ('released', models.DateField()),
                ('slug', models.SlugField()),
                ('artist', models.ManyToManyField(to='main.artist')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='album_covers')),
                ('detail', ckeditor.fields.RichTextField(blank=True)),
                ('released', models.DateField()),
                ('recorder', models.CharField(blank=True, max_length=30)),
                ('length', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('artist', models.ManyToManyField(to='main.artist')),
                ('songs', models.ManyToManyField(to='main.song')),
            ],
        ),
    ]
