# Generated by Django 5.1.4 on 2024-12-20 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_artist_genre_label_remove_event_event_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='is_band_member',
        ),
    ]
